version: '3'
services:
  mysql:
    build: 
      context: ./DB
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: rootadmin
      MYSQL_DATABASE: IAC
    volumes:
      - mysql-data:/var/lib/mysql
      - ./DB/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - iac-network
    ports:
      - "3308:3306"
    command: --default-authentication-plugin=mysql_native_password
  php-apache:
    build: 
      context: ./PHP
    ports:
      - "80:80"
    volumes:
      - ./PHP:/var/www/html
    depends_on:
      - mysql
    networks:
      - iac-network
volumes:
  mysql-data:
networks:
  iac-network: